### ISSUE TITLE
ALIASES property

### ISSUE THREAD

**Issue by teuhc** [ysb33r/doxygen-gradle-plugin#17]
First, thank you for the plugins.
We are trying to use the ALIASES property in our gradle file but we have an error message 👍 

> What went wrong:
> problem occurred evaluating script.
> 'aliases' is not a valid configuration option

**Comment by ysb33r** [comment]
Can you provide a reproducible example?

**Comment by teuhc** [comment]
I added the following line to task :

`aliases                 "ChangeLog=\\xrefitem ChangeLogs \"ChangeLog\" \"ChangeLogs\"  "`

**Comment by allenluce** [comment]
This would be a useful thing to have.

**Comment by ysb33r** [comment]
In 0.6.
