### ISSUE TITLE
plugin publishing

### ISSUE THREAD

**Issue by shrom** [ysb33r/doxygen-gradle-plugin#18]
The documentation specifies plugin as following:

apply plugin: "org.ysb33r.doxygen"

However "https://plugins.gradle.org/m2/" contains an empty 
https://plugins.gradle.org/m2/org/ysb33r/doxygen/

While 
https://plugins.gradle.org/m2/org/ysb33r/gradle/
has the plugin:
https://plugins.gradle.org/m2/org/ysb33r/gradle/doxygen-gradle-plugin/

**Comment by ysb33r** [comment]
It's the way the plugin portal operates.
