### ISSUE TITLE
No such property: PROJECT_NUMBER when running doxygen task

### ISSUE THREAD

**Issue by c4sh** [ysb33r/doxygen-gradle-plugin#19]
I'm seeing this error: 
> No such property: PROJECT_NUMBER for class: org.ysb33r.gradle.doxygen.impl.DoxygenProperties

when running the doxygen task.
I'm configuring the task on a project.afterEvaluate closure, maybe that has to do with it but don't know a solution for that.

Full stacktrace attached as .txt
[stackTrace.txt](https://github.com/ysb33r/doxygen-gradle-plugin/files/2205580/stackTrace.txt)

**Comment by ysb33r** [comment]
Did you set `project.version`? That is the default value for Doxygen's `PROJECT_NUMBER`.

**Comment by c4sh** [comment]
Yes! that was it. Thanks a lot.
