### ISSUE TITLE
FTP server for doxygen executables no longer exists

### ISSUE THREAD

**Issue by ThadHouse** [ysb33r/doxygen-gradle-plugin#20]
The ftp site where the doxygen executables were downloaded from no longer exists, nor does the download links from the doxygen website.

http://www.stack.nl/~dimitri/doxygen/download.html

Does anyone have a mirror?

**Comment by FriedrichFroebel** [comment]
Just cross-referencing the issue you filed against the Doxygen project itself for the record: https://github.com/doxygen/doxygen/issues/6654

**Comment by PeterJohnson** [comment]
It looks like all the files are on SourceForge.  https://sourceforge.net/projects/doxygen/files/rel-1.8.14/

**Comment by ysb33r** [comment]
Is a fix needed for this in the plugin or will it be republished to the original site?

**Comment by PeterJohnson** [comment]
From the doxygen bug report discussion (linked above) “The www.stack.nl address has been disabled as stack.nl stopped the service.”  So a fix is needed in the plugin.

**Comment by ysb33r** [comment]
OK. I'll have a look at it. Unless someone can get there before me and submit a PR.

**Comment by ysb33r** [comment]
I hope to get a 0.5 release out later today.

**Comment by ysb33r** [comment]
0.5 is out. Please have a play.
