### ISSUE TITLE
Error on README.adoc

### ISSUE THREAD

**Issue by albert-github** [ysb33r/doxygen-gradle-plugin#21]
In the README.adoc I see a few problems

- the address of doxygen is incomplete (now `www.doxygen` should be www.doxygen.org or www.doxygen.nl)
- on some places doxygen is misspelled i.e. Doxygen whilst on other places the correct `doxygen` is used.
- the conversion of `[source,groovy]` results in `[source,groovy[`
- incomplete sentence "... patterns as per how the Doxygen project names t"
- minor, the text mentions 1.8.8 , which is from August 2014, better would be to refer to the current version 1.8.14

**Comment by albert-github** [comment]
I looked now in the development branch:
- I don't see a reference to the doxygen website (for the executable)
- On some places there is still "Doxygen" instead of "doxygen"

**Comment by ysb33r** [comment]
Can you create a little PR with the changes you want to see? It will help.

**Comment by albert-github** [comment]
I'll have a look (will take some time, hopefully before the end of the day).

Question: The master branch is quite different from the release branch (and less frequently updated), any reason for this strategy?

**Comment by ysb33r** [comment]
No, it is probably from some legacy approach. Master should be last release or soon-to-be-released. Release branch should simply be last released.

**Comment by albert-github** [comment]
Sorry some confusion on my side I meant Master and development branches.

**Comment by ysb33r** [comment]
Thanks for the PR.
