### ISSUE TITLE
Make this plugin platform independent

### ISSUE THREAD

**Issue by jaredsburrows** [ysb33r/doxygen-gradle-plugin#3]
Currently you have to have doxygen downloaded/installed on your CI server or locally on your machine.

Have you looked into bundling doxygen in your plugin?

**Comment by ysb33r** [comment]
I have followed the Gradl econvention for native tools of having it installed.

However, I have given thought to having it automatically downloaded at build time it it does not exists locally and a binary for the platform exists. Might still do this someday in the future (and not just for this plugin).

**Comment by jaredsburrows** [comment]
@ysb33r Thanks. I just do not want to upload a binary for doxygen into the CI or have to hardcode a path to one for the DSL of your plugin.

**Comment by ysb33r** [comment]
@jaredsburrows I now have some working code which will support this under Linux, MacOSX and Windows. I would hope to have it in the next release, but it is dependent on the first version of [the Grolifant library](https://github.com/ysb33r/grolifant) being released.

**Comment by jaredsburrows** [comment]
@ysb33r That sounds cool! Maybe publish a snapshot of the `Grolifant` library with a snapshot of the this plugin for testing.

**Comment by ysb33r** [comment]
> That sounds cool! Maybe publish a snapshot of the Grolifant library with a snapshot of the this plugin for testing.

Grolifant 0.1 was released today. Hopefully will have everything released in this week. (Current progress is under gradle30 branch).

**Comment by ysb33r** [comment]
@jaredsburrows Have a go and see how 0.3 works for you.
